version: "2"

linters:
  default: all
  disable:
    - exhaustruct         # Проверяет, что все поля структуры инициализированы при её создании.
    - forbidigo           # Запрещает использование определённых выражений или функций, указанных в конфигурации.
    - funcorder           # Проверяет порядок объявления функций для улучшения читаемости.
    - ireturn             # Анализирует возвращаемые значения функций на соответствие ожиданиям.
    - mnd                 # Обнаруживает "магические числа" в коде, предлагая заменить их на именованные константы.
    - tagliatelle         # Проверяет стиль и форматирование тегов структур.
    - varnamelen          # Проверяет длину имён переменных, чтобы избежать слишком коротких или слишком длинных имён.
    - depguard
    - wsl                 # устарел и заменен на wsl_v5

  # Тонкая настройка нужного линтера (если есть)
  # См. отдельную секцию документации https://golangci-lint.run/usage/linters/#linters-configuration
  settings:
    gocritic:
      enabled-tags:
        - diagnostic
        - style
        - experimental
        - opinionated
      disabled-checks:
        - whyNoLint

  # Определяет набор правил для игнорирования предупреждений.
  # Анализ при этом выполняется, поэтому ошибки "typecheck" всё равно будут выдаваться.
  exclusions:
    # Режим анализа сгенерированных файлов.
    # - `lax`:  Исключает файлы, содержащие строки вроде `autogenerated file`, `code generated`, `do not edit` и т.п.
    generated: lax

    # Предустановленные правила исключения.
    presets:
      - comments                  # отключает типичные замечания к комментариям
      - std-error-handling        # отключает незначительные ошибки при обработке ошибок

    # Пути к файлам, которые будут анализироваться, но их ошибки не будут выводиться.
    paths:
      - _test.go
      - gen/
      - test/integration/

    # Исключающие правила по пути, линтеру, тексту и исходнику.
    rules:
      # Исключаем определённые линтеры для файлов по пути
      - path: pkg/logger
        linters:
          - zerologlint

      - path: internal/app
        linters:
          - contextcheck

      - path: internal/controller/grpc/
        linters:
          - wrapcheck

      - path: internal/controller/http/v2
        linters:
          - wrapcheck

      # Исключаем некоторые сообщения по тексту ошибки
      - linters:
          - err113
        text: "do not define dynamic errors"

      # Исключаем некоторые сообщения по коду в файле
      - linters:
          - lll
        source: "^//go:generate "

# Опции форматирования кода.
formatters:
  enable:
    - gci          # Упорядочивает импорты по группам (стандартные, сторонние, локальные)
    - gofmt        # Стандартный инструмент форматирования кода Go
    - gofumpt      # Более строгая версия gofmt с улучшенной читаемостью
    - goimports    # Форматирует код и автоматически управляет импортами

  # Настройки для форматтеров.
  # См. раздел документации https://golangci-lint.run/usage/formatters/
  settings:
    gofumpt:
      extra-rules: true
    gci:
      sections:
        - standard # Standard section: captures all standard packages.
        - default # Default section: contains all imports that could not be matched to another section type.
        - blank # Blank section: contains all blank imports. This section is not present unless explicitly enabled.
        - dot # Dot section: contains all dot imports. This section is not present unless explicitly enabled.
        - localmodule # Local module section: contains all local packages. This section is not present unless explicitly enabled.
        - alias # Alias section: contains all alias imports. This section is not present unless explicitly enabled.

  exclusions:
    # Режим анализа сгенерированных файлов.
    # - `disable`: не исключать сгенерированные файлы вообще
    generated: disable

    # Пути к файлам, которые исключаются из форматирования.
    paths:
      - gen

# Опции конфигурации линтера.
issues:
  # Максимальное количество одинаковых сообщений об ошибке.
  # Установите 0, чтобы отключить ограничение.
  # По умолчанию: 3
  max-same-issues: 0

  # Автоматически исправлять найденные ошибки (если поддерживается линтером).
  fix: true

# Опции конфигурации вывода результатов.
output:
  # Форматы, в которых выводятся найденные проблемы.
  formats:
    # Вывод в текстовом формате с цветами, номерами строк и названиями линтеров.
    # Это формат используется по умолчанию.
    text:
      # Куда выводить результаты: `stdout`, `stderr` или путь к файлу.
      # По умолчанию: stdout
      path: stdout

  # Определяет порядок сортировки результатов.
  sort-order:
    - linter
    - file # путь к файлу, строка, колонка

# Опции для запуска анализа.
run:
  # Таймаут для всего процесса анализа
  timeout: 5m

  # Режим, используемый для вычисления относительных путей.
  # Используется в исключениях, Go-плагинах и некоторых линтерах.
  # - `gomod`: пути считаются относительно директории с `go.mod`.
  relative-path-mode: gomod

  # Разрешить одновременный запуск нескольких экземпляров golangci-lint.
  allow-parallel-runners: true

  # Разрешить запуск нескольких экземпляров, но синхронизировать их по блокировке.
  allow-serial-runners: true