run:
  timeout: 2m                     # Устанавливает максимальное время выполнения линтера на 2 минуты, после чего он будет остановлен

issues:
  exclude-files:                  # Игнорирует файлы, которые соответствуют регулярному выражению .*mocks.+
    - ".*mocks.+"                 # это полезно, чтобы не проверять автоматически сгенерированные моки
  exclude-rules:                  # Здесь задаются исключения для определённых проверок
    - path: config/config         # Исключение применяется к файлам, находящимся в директории config/config
      linters:                    # для этих файлов отключается проверка указанными линтерами
        - govet

output:
  formats:
    - format: colored-line-number # Формат вывода для интеграции с GitHub Actions

linters-settings:                 # В этой секции настраиваются параметры для конкретных линтеров
  cyclop:                         # Линтер для проверки цикломатической сложности функций
    max-complexity: 15            # Максимально допустимая сложность функции
  funlen:                         # Линтер для проверки длины функций
    lines: 80                     # Максимальное количество строк в функции
  errcheck:                       # Линтер для проверки обработки ошибок
    check-type-assertions: true   # Проверяет, обрабатываются ли ошибки при type-assertions
    check-blank: true             # Проверяет, игнорируются ли ошибки
  goconst:                        # Линтер для поиска повторяющихся строковых и числовых констант
    min-len: 2                    # Минимальная длина строки для проверки
    min-occurrences: 2            # Минимальное количество повторений для обнаружения
    ignore-tests: true            # Игнорировать тестовые файлы
    match-constant: false         # Не проверять совпадение с существующими константами
    numbers: true                 # Проверять числовые константы
    min: 2                        # Минимальное значение для числовых констант
    max: 2                        # Максимальное значение для числовых констант
  gocritic:                       # Линтер для анализа кода на основе настраиваемых правил
    enabled-tags:                 # Включены правила со следующими тегами
      - diagnostic
      - experimental
      - opinionated
      - performance
      - style
    disabled-checks:              # Отключены конкретные проверки
      - dupImport                 # Проверка на дублирование импортов
      - unnecessaryBlock          # Проверка на избыточные блоки кода
      - whyNoLint                 # Проверка на отсутствие комментариев //nolint
  gofumpt:                        # Линтер для форматирования кода с дополнительными строгими правилами
    extra-rules: true             # Включены дополнительные правила форматирования
  misspell:                       # Линтер для поиска орфографических ошибок
    locale: US                    # Используется американский английский для проверки

linters:                          # В этой секции указывается какие линтеры должны быть включены, а какие отключены
  enable-all: true                # Включены все линтеры по умолчанию
  disable:                        # Отключены следующие линтеры
    - mnd
    - gci                         # Управляет порядком импортов, но gofumpt делает это лучше
    - tenv                        # deprecated, но пока не удаленный линтер, поэтому он прописан здесь
    - lll                         # мало пользы
    - nolintlint                  # мало пользы
    - prealloc                    # преждевременная оптимизация
    - paralleltest                # преждевременная оптимизация
    - exhaustruct                 # теряется удобство, придётся инициализировать все поля структуры нулевыми значениями
    - nonamedreturns              # не дает возможности использовать именованные возвраты там где это нужно
    - varnamelen                  # идея интересная, но не хватает гибкости в настройках, такое сложно автоматизировать
    - promlinter                  # диктует как называть переменные метрик
    - tagliatelle                 # у нас могут быть разные кейсы, обобщить нельзя, в каждом проекте будут свои настройки
    - dupl                        # не приносит пользы
    - ireturn
    - tagalign
    - depguard
    - dupword