// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/google/uuid"

	mock "github.com/stretchr/testify/mock"

	"github.com/mozhaykin/my-app/internal/domain"
	"github.com/mozhaykin/my-app/internal/dto"
)

// NewPostgres creates a new instance of Postgres. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewPostgres(t interface {
	mock.TestingT
	Cleanup(func())
},
) *Postgres {
	mock := &Postgres{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// Postgres is an autogenerated mock type for the Postgres type
type Postgres struct {
	mock.Mock
}

type Postgres_Expecter struct {
	mock *mock.Mock
}

func (_m *Postgres) EXPECT() *Postgres_Expecter {
	return &Postgres_Expecter{mock: &_m.Mock}
}

// ClearOutbox provides a mock function for the type Postgres
func (_mock *Postgres) ClearOutbox(ctx context.Context, ids []uuid.UUID) error {
	ret := _mock.Called(ctx, ids)

	if len(ret) == 0 {
		panic("no return value specified for ClearOutbox")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, []uuid.UUID) error); ok {
		r0 = returnFunc(ctx, ids)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// Postgres_ClearOutbox_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ClearOutbox'
type Postgres_ClearOutbox_Call struct {
	*mock.Call
}

// ClearOutbox is a helper method to define mock.On call
//   - ctx
//   - ids
func (_e *Postgres_Expecter) ClearOutbox(ctx, ids interface{}) *Postgres_ClearOutbox_Call {
	return &Postgres_ClearOutbox_Call{Call: _e.mock.On("ClearOutbox", ctx, ids)}
}

func (_c *Postgres_ClearOutbox_Call) Run(run func(ctx context.Context, ids []uuid.UUID)) *Postgres_ClearOutbox_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].([]uuid.UUID))
	})
	return _c
}

func (_c *Postgres_ClearOutbox_Call) Return(err error) *Postgres_ClearOutbox_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *Postgres_ClearOutbox_Call) RunAndReturn(run func(ctx context.Context, ids []uuid.UUID) error) *Postgres_ClearOutbox_Call {
	_c.Call.Return(run)
	return _c
}

// CreateProfile provides a mock function for the type Postgres
func (_mock *Postgres) CreateProfile(ctx context.Context, profile domain.Profile) error {
	ret := _mock.Called(ctx, profile)

	if len(ret) == 0 {
		panic("no return value specified for CreateProfile")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.Profile) error); ok {
		r0 = returnFunc(ctx, profile)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// Postgres_CreateProfile_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateProfile'
type Postgres_CreateProfile_Call struct {
	*mock.Call
}

// CreateProfile is a helper method to define mock.On call
//   - ctx
//   - profile
func (_e *Postgres_Expecter) CreateProfile(ctx, profile interface{}) *Postgres_CreateProfile_Call {
	return &Postgres_CreateProfile_Call{Call: _e.mock.On("CreateProfile", ctx, profile)}
}

func (_c *Postgres_CreateProfile_Call) Run(run func(ctx context.Context, profile domain.Profile)) *Postgres_CreateProfile_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(domain.Profile))
	})
	return _c
}

func (_c *Postgres_CreateProfile_Call) Return(err error) *Postgres_CreateProfile_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *Postgres_CreateProfile_Call) RunAndReturn(run func(ctx context.Context, profile domain.Profile) error) *Postgres_CreateProfile_Call {
	_c.Call.Return(run)
	return _c
}

// CreateProperty provides a mock function for the type Postgres
func (_mock *Postgres) CreateProperty(ctx context.Context, property domain.Property) error {
	ret := _mock.Called(ctx, property)

	if len(ret) == 0 {
		panic("no return value specified for CreateProperty")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.Property) error); ok {
		r0 = returnFunc(ctx, property)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// Postgres_CreateProperty_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateProperty'
type Postgres_CreateProperty_Call struct {
	*mock.Call
}

// CreateProperty is a helper method to define mock.On call
//   - ctx
//   - property
func (_e *Postgres_Expecter) CreateProperty(ctx, property interface{}) *Postgres_CreateProperty_Call {
	return &Postgres_CreateProperty_Call{Call: _e.mock.On("CreateProperty", ctx, property)}
}

func (_c *Postgres_CreateProperty_Call) Run(run func(ctx context.Context, property domain.Property)) *Postgres_CreateProperty_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(domain.Property))
	})
	return _c
}

func (_c *Postgres_CreateProperty_Call) Return(err error) *Postgres_CreateProperty_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *Postgres_CreateProperty_Call) RunAndReturn(run func(ctx context.Context, property domain.Property) error) *Postgres_CreateProperty_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteProfile provides a mock function for the type Postgres
func (_mock *Postgres) DeleteProfile(ctx context.Context, profileID uuid.UUID) error {
	ret := _mock.Called(ctx, profileID)

	if len(ret) == 0 {
		panic("no return value specified for DeleteProfile")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) error); ok {
		r0 = returnFunc(ctx, profileID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// Postgres_DeleteProfile_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteProfile'
type Postgres_DeleteProfile_Call struct {
	*mock.Call
}

// DeleteProfile is a helper method to define mock.On call
//   - ctx
//   - profileID
func (_e *Postgres_Expecter) DeleteProfile(ctx, profileID interface{}) *Postgres_DeleteProfile_Call {
	return &Postgres_DeleteProfile_Call{Call: _e.mock.On("DeleteProfile", ctx, profileID)}
}

func (_c *Postgres_DeleteProfile_Call) Run(run func(ctx context.Context, profileID uuid.UUID)) *Postgres_DeleteProfile_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *Postgres_DeleteProfile_Call) Return(err error) *Postgres_DeleteProfile_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *Postgres_DeleteProfile_Call) RunAndReturn(run func(ctx context.Context, profileID uuid.UUID) error) *Postgres_DeleteProfile_Call {
	_c.Call.Return(run)
	return _c
}

// GetProfile provides a mock function for the type Postgres
func (_mock *Postgres) GetProfile(ctx context.Context, profileID uuid.UUID) (domain.Profile, error) {
	ret := _mock.Called(ctx, profileID)

	if len(ret) == 0 {
		panic("no return value specified for GetProfile")
	}

	var r0 domain.Profile
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) (domain.Profile, error)); ok {
		return returnFunc(ctx, profileID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) domain.Profile); ok {
		r0 = returnFunc(ctx, profileID)
	} else {
		r0 = ret.Get(0).(domain.Profile)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = returnFunc(ctx, profileID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// Postgres_GetProfile_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetProfile'
type Postgres_GetProfile_Call struct {
	*mock.Call
}

// GetProfile is a helper method to define mock.On call
//   - ctx
//   - profileID
func (_e *Postgres_Expecter) GetProfile(ctx, profileID interface{}) *Postgres_GetProfile_Call {
	return &Postgres_GetProfile_Call{Call: _e.mock.On("GetProfile", ctx, profileID)}
}

func (_c *Postgres_GetProfile_Call) Run(run func(ctx context.Context, profileID uuid.UUID)) *Postgres_GetProfile_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *Postgres_GetProfile_Call) Return(profile domain.Profile, err error) *Postgres_GetProfile_Call {
	_c.Call.Return(profile, err)
	return _c
}

func (_c *Postgres_GetProfile_Call) RunAndReturn(run func(ctx context.Context, profileID uuid.UUID) (domain.Profile, error)) *Postgres_GetProfile_Call {
	_c.Call.Return(run)
	return _c
}

// GetProfiles provides a mock function for the type Postgres
func (_mock *Postgres) GetProfiles(ctx context.Context, input dto.GetProfilesInput) ([]domain.Profile, error) {
	ret := _mock.Called(ctx, input)

	if len(ret) == 0 {
		panic("no return value specified for GetProfiles")
	}

	var r0 []domain.Profile
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, dto.GetProfilesInput) ([]domain.Profile, error)); ok {
		return returnFunc(ctx, input)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, dto.GetProfilesInput) []domain.Profile); ok {
		r0 = returnFunc(ctx, input)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.Profile)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, dto.GetProfilesInput) error); ok {
		r1 = returnFunc(ctx, input)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// Postgres_GetProfiles_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetProfiles'
type Postgres_GetProfiles_Call struct {
	*mock.Call
}

// GetProfiles is a helper method to define mock.On call
//   - ctx
//   - input
func (_e *Postgres_Expecter) GetProfiles(ctx, input interface{}) *Postgres_GetProfiles_Call {
	return &Postgres_GetProfiles_Call{Call: _e.mock.On("GetProfiles", ctx, input)}
}

func (_c *Postgres_GetProfiles_Call) Run(run func(ctx context.Context, input dto.GetProfilesInput)) *Postgres_GetProfiles_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(dto.GetProfilesInput))
	})
	return _c
}

func (_c *Postgres_GetProfiles_Call) Return(profiles []domain.Profile, err error) *Postgres_GetProfiles_Call {
	_c.Call.Return(profiles, err)
	return _c
}

func (_c *Postgres_GetProfiles_Call) RunAndReturn(run func(ctx context.Context, input dto.GetProfilesInput) ([]domain.Profile, error)) *Postgres_GetProfiles_Call {
	_c.Call.Return(run)
	return _c
}

// ReadOutbox provides a mock function for the type Postgres
func (_mock *Postgres) ReadOutbox(ctx context.Context, limit int) ([]domain.Event, error) {
	ret := _mock.Called(ctx, limit)

	if len(ret) == 0 {
		panic("no return value specified for ReadOutbox")
	}

	var r0 []domain.Event
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int) ([]domain.Event, error)); ok {
		return returnFunc(ctx, limit)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int) []domain.Event); ok {
		r0 = returnFunc(ctx, limit)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.Event)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int) error); ok {
		r1 = returnFunc(ctx, limit)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// Postgres_ReadOutbox_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ReadOutbox'
type Postgres_ReadOutbox_Call struct {
	*mock.Call
}

// ReadOutbox is a helper method to define mock.On call
//   - ctx
//   - limit
func (_e *Postgres_Expecter) ReadOutbox(ctx, limit interface{}) *Postgres_ReadOutbox_Call {
	return &Postgres_ReadOutbox_Call{Call: _e.mock.On("ReadOutbox", ctx, limit)}
}

func (_c *Postgres_ReadOutbox_Call) Run(run func(ctx context.Context, limit int)) *Postgres_ReadOutbox_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int))
	})
	return _c
}

func (_c *Postgres_ReadOutbox_Call) Return(events []domain.Event, err error) *Postgres_ReadOutbox_Call {
	_c.Call.Return(events, err)
	return _c
}

func (_c *Postgres_ReadOutbox_Call) RunAndReturn(run func(ctx context.Context, limit int) ([]domain.Event, error)) *Postgres_ReadOutbox_Call {
	_c.Call.Return(run)
	return _c
}

// SaveOutbox provides a mock function for the type Postgres
func (_mock *Postgres) SaveOutbox(ctx context.Context, events ...domain.Event) error {
	var tmpRet mock.Arguments
	if len(events) > 0 {
		tmpRet = _mock.Called(ctx, events)
	} else {
		tmpRet = _mock.Called(ctx)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for SaveOutbox")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, ...domain.Event) error); ok {
		r0 = returnFunc(ctx, events...)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// Postgres_SaveOutbox_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SaveOutbox'
type Postgres_SaveOutbox_Call struct {
	*mock.Call
}

// SaveOutbox is a helper method to define mock.On call
//   - ctx
//   - events
func (_e *Postgres_Expecter) SaveOutbox(ctx interface{}, events ...interface{}) *Postgres_SaveOutbox_Call {
	return &Postgres_SaveOutbox_Call{Call: _e.mock.On("SaveOutbox",
		append([]interface{}{ctx}, events...)...)}
}

func (_c *Postgres_SaveOutbox_Call) Run(run func(ctx context.Context, events ...domain.Event)) *Postgres_SaveOutbox_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := args[1].([]domain.Event)
		run(args[0].(context.Context), variadicArgs...)
	})
	return _c
}

func (_c *Postgres_SaveOutbox_Call) Return(err error) *Postgres_SaveOutbox_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *Postgres_SaveOutbox_Call) RunAndReturn(run func(ctx context.Context, events ...domain.Event) error) *Postgres_SaveOutbox_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateProfile provides a mock function for the type Postgres
func (_mock *Postgres) UpdateProfile(ctx context.Context, profile domain.Profile) error {
	ret := _mock.Called(ctx, profile)

	if len(ret) == 0 {
		panic("no return value specified for UpdateProfile")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.Profile) error); ok {
		r0 = returnFunc(ctx, profile)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// Postgres_UpdateProfile_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateProfile'
type Postgres_UpdateProfile_Call struct {
	*mock.Call
}

// UpdateProfile is a helper method to define mock.On call
//   - ctx
//   - profile
func (_e *Postgres_Expecter) UpdateProfile(ctx, profile interface{}) *Postgres_UpdateProfile_Call {
	return &Postgres_UpdateProfile_Call{Call: _e.mock.On("UpdateProfile", ctx, profile)}
}

func (_c *Postgres_UpdateProfile_Call) Run(run func(ctx context.Context, profile domain.Profile)) *Postgres_UpdateProfile_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(domain.Profile))
	})
	return _c
}

func (_c *Postgres_UpdateProfile_Call) Return(err error) *Postgres_UpdateProfile_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *Postgres_UpdateProfile_Call) RunAndReturn(run func(ctx context.Context, profile domain.Profile) error) *Postgres_UpdateProfile_Call {
	_c.Call.Return(run)
	return _c
}

// NewRedis creates a new instance of Redis. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewRedis(t interface {
	mock.TestingT
	Cleanup(func())
},
) *Redis {
	mock := &Redis{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// Redis is an autogenerated mock type for the Redis type
type Redis struct {
	mock.Mock
}

type Redis_Expecter struct {
	mock *mock.Mock
}

func (_m *Redis) EXPECT() *Redis_Expecter {
	return &Redis_Expecter{mock: &_m.Mock}
}

// DeleteCache provides a mock function for the type Redis
func (_mock *Redis) DeleteCache(ctx context.Context, id uuid.UUID) error {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for DeleteCache")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) error); ok {
		r0 = returnFunc(ctx, id)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// Redis_DeleteCache_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteCache'
type Redis_DeleteCache_Call struct {
	*mock.Call
}

// DeleteCache is a helper method to define mock.On call
//   - ctx
//   - id
func (_e *Redis_Expecter) DeleteCache(ctx, id interface{}) *Redis_DeleteCache_Call {
	return &Redis_DeleteCache_Call{Call: _e.mock.On("DeleteCache", ctx, id)}
}

func (_c *Redis_DeleteCache_Call) Run(run func(ctx context.Context, id uuid.UUID)) *Redis_DeleteCache_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *Redis_DeleteCache_Call) Return(err error) *Redis_DeleteCache_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *Redis_DeleteCache_Call) RunAndReturn(run func(ctx context.Context, id uuid.UUID) error) *Redis_DeleteCache_Call {
	_c.Call.Return(run)
	return _c
}

// GetCache provides a mock function for the type Redis
func (_mock *Redis) GetCache(ctx context.Context, id uuid.UUID) (domain.Profile, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetCache")
	}

	var r0 domain.Profile
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) (domain.Profile, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) domain.Profile); ok {
		r0 = returnFunc(ctx, id)
	} else {
		r0 = ret.Get(0).(domain.Profile)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// Redis_GetCache_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetCache'
type Redis_GetCache_Call struct {
	*mock.Call
}

// GetCache is a helper method to define mock.On call
//   - ctx
//   - id
func (_e *Redis_Expecter) GetCache(ctx, id interface{}) *Redis_GetCache_Call {
	return &Redis_GetCache_Call{Call: _e.mock.On("GetCache", ctx, id)}
}

func (_c *Redis_GetCache_Call) Run(run func(ctx context.Context, id uuid.UUID)) *Redis_GetCache_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *Redis_GetCache_Call) Return(profile domain.Profile, err error) *Redis_GetCache_Call {
	_c.Call.Return(profile, err)
	return _c
}

func (_c *Redis_GetCache_Call) RunAndReturn(run func(ctx context.Context, id uuid.UUID) (domain.Profile, error)) *Redis_GetCache_Call {
	_c.Call.Return(run)
	return _c
}

// IsIdempotencyKeyExists provides a mock function for the type Redis
func (_mock *Redis) IsIdempotencyKeyExists(ctx context.Context, idempotencyKey string) bool {
	ret := _mock.Called(ctx, idempotencyKey)

	if len(ret) == 0 {
		panic("no return value specified for IsIdempotencyKeyExists")
	}

	var r0 bool
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) bool); ok {
		r0 = returnFunc(ctx, idempotencyKey)
	} else {
		r0 = ret.Get(0).(bool)
	}
	return r0
}

// Redis_IsIdempotencyKeyExists_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IsIdempotencyKeyExists'
type Redis_IsIdempotencyKeyExists_Call struct {
	*mock.Call
}

// IsIdempotencyKeyExists is a helper method to define mock.On call
//   - ctx
//   - idempotencyKey
func (_e *Redis_Expecter) IsIdempotencyKeyExists(ctx, idempotencyKey interface{}) *Redis_IsIdempotencyKeyExists_Call {
	return &Redis_IsIdempotencyKeyExists_Call{Call: _e.mock.On("IsIdempotencyKeyExists", ctx, idempotencyKey)}
}

func (_c *Redis_IsIdempotencyKeyExists_Call) Run(run func(ctx context.Context, idempotencyKey string)) *Redis_IsIdempotencyKeyExists_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *Redis_IsIdempotencyKeyExists_Call) Return(b bool) *Redis_IsIdempotencyKeyExists_Call {
	_c.Call.Return(b)
	return _c
}

func (_c *Redis_IsIdempotencyKeyExists_Call) RunAndReturn(run func(ctx context.Context, idempotencyKey string) bool) *Redis_IsIdempotencyKeyExists_Call {
	_c.Call.Return(run)
	return _c
}

// SetCache provides a mock function for the type Redis
func (_mock *Redis) SetCache(ctx context.Context, profile domain.Profile) error {
	ret := _mock.Called(ctx, profile)

	if len(ret) == 0 {
		panic("no return value specified for SetCache")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.Profile) error); ok {
		r0 = returnFunc(ctx, profile)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// Redis_SetCache_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetCache'
type Redis_SetCache_Call struct {
	*mock.Call
}

// SetCache is a helper method to define mock.On call
//   - ctx
//   - profile
func (_e *Redis_Expecter) SetCache(ctx, profile interface{}) *Redis_SetCache_Call {
	return &Redis_SetCache_Call{Call: _e.mock.On("SetCache", ctx, profile)}
}

func (_c *Redis_SetCache_Call) Run(run func(ctx context.Context, profile domain.Profile)) *Redis_SetCache_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(domain.Profile))
	})
	return _c
}

func (_c *Redis_SetCache_Call) Return(err error) *Redis_SetCache_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *Redis_SetCache_Call) RunAndReturn(run func(ctx context.Context, profile domain.Profile) error) *Redis_SetCache_Call {
	_c.Call.Return(run)
	return _c
}

// NewKafka creates a new instance of Kafka. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewKafka(t interface {
	mock.TestingT
	Cleanup(func())
},
) *Kafka {
	mock := &Kafka{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// Kafka is an autogenerated mock type for the Kafka type
type Kafka struct {
	mock.Mock
}

type Kafka_Expecter struct {
	mock *mock.Mock
}

func (_m *Kafka) EXPECT() *Kafka_Expecter {
	return &Kafka_Expecter{mock: &_m.Mock}
}

// Produce provides a mock function for the type Kafka
func (_mock *Kafka) Produce(ctx context.Context, events []domain.Event) error {
	ret := _mock.Called(ctx, events)

	if len(ret) == 0 {
		panic("no return value specified for Produce")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, []domain.Event) error); ok {
		r0 = returnFunc(ctx, events)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// Kafka_Produce_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Produce'
type Kafka_Produce_Call struct {
	*mock.Call
}

// Produce is a helper method to define mock.On call
//   - ctx
//   - events
func (_e *Kafka_Expecter) Produce(ctx, events interface{}) *Kafka_Produce_Call {
	return &Kafka_Produce_Call{Call: _e.mock.On("Produce", ctx, events)}
}

func (_c *Kafka_Produce_Call) Run(run func(ctx context.Context, events []domain.Event)) *Kafka_Produce_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].([]domain.Event))
	})
	return _c
}

func (_c *Kafka_Produce_Call) Return(err error) *Kafka_Produce_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *Kafka_Produce_Call) RunAndReturn(run func(ctx context.Context, events []domain.Event) error) *Kafka_Produce_Call {
	_c.Call.Return(run)
	return _c
}
