# yaml-language-server: $schema=https://raw.githubusercontent.com/oapi-codegen/oapi-codegen/HEAD/configuration-schema.json
package: server
generate:
  chi-server: true
  models: true
  strict-server: true   # включает более строгую валидацию и генерирует удобные dto структуры
output: server.gen.go   # название файла, который будет сгенерирован
output-options:
  name-normalizer: ToCamelCaseWithInitialisms # с этой опцией переменные-абревиатуры, например ID, будут сгенерированы большими буквами
                                              # а без этой опции будет Id.