# yaml-language-server: $schema=https://raw.githubusercontent.com/oapi-codegen/oapi-codegen/HEAD/configuration-schema.json
package: server    # название пакета, который будет сгенерирован
generate:
  chi-server: true      # какой сервер использовать
  models: true          # генерировать или нет модели
  strict-server: true   # рекомендуется включать, чтобы код был более подробный (сгенерятся dto и будут использованы)
output: server.gen.go   # название файла, который будет сгенерирован
output-options:
  name-normalizer: ToCamelCaseWithInitialisms # с этой опцией переменные-абревиатуры, например ID, будут сгенерированы большими буквами
                                              # а без этой опции будет Id.